### ISSUE TITLE
Ny fane "Datadump"

### ISSUE THREAD

**Issue by areedv** [Rapporteket/NORIC#10]
som tilbyr nedlasting av data som csv

**Comment by areedv** [comment]
csv gjennom readr...

**Comment by ellnyg** [comment]
readr::write_excel_csv2 ("write_excel_csv() and write_excel_csv2() also include a UTF-8 Byte order mark which indicates to Excel the csv is UTF-8 encoded.")

**Comment by areedv** [comment]
Foreløpig er dette løst gjennom ```rio::export()``` så får vi heller endre om det blir behov for det
