### ISSUE TITLE
Ingen data fra datadump

### ISSUE THREAD

**Issue by areedv** [Rapporteket/NORIC#100]
Misstenker at feilen ligger [her](https://github.com/Rapporteket/NORIC/blob/ed4d5828a3dea08c03b5ecf633e8eff86a0124b1/R/getDataDump.R#L408)

**Comment by maraut90** [comment]
@areedv Har du et forslag til fjerning av disse to variablene fra datadumpen?

**Comment by areedv** [comment]
End of function
```r

# Midlertidig fjerning av variabler i daatadumpen
  tab %<>% dplyr::select_if(!names(.data) %in% c("Avdod", "AvdodDato"))

  # Returnerer tabell (med eller uten felt fra fO)
  return(tab)

}
```

may be replaced by
```r

dplyr::select(tab, !contains(c("Avdod", "AvdodDato")))

}
```

This will return ```tab``` from the function excluding ```tab$Avdod``` and ```tab$AvdodDato``` if they exists
