### ISSUE TITLE
Månedsrapport - forside + bunntekst + tekst

### ISSUE THREAD

**Issue by skkrist** [Rapporteket/NORIC#108]
Legge til forside i måndesrapportene (Stent + månedsrapport + Kvalitetsindikatorer). 
Med dato, lastet ned av, rolle logget inn, automatisk tilsent.. 
+ evt bunntekst med teksten "lastet ned av ...  den ..."

Legge til tekst i rapporten. Med datagrunnlag for figur/tekst + eventuell forklaring.

**Comment by areedv** [comment]
May depend on updated in rapbase...

**Comment by skkrist** [comment]
v.2.5.0 Kvalitetsindikatorer OK
Stent + prosedyrer igjen

**Comment by skkrist** [comment]
@maraut90 Får du med denne i "Sammenslå stent og prosedyre" ?

**Comment by maraut90** [comment]
Må vel også gjøre dette for rapporten "Aktivitet"?
