### ISSUE TITLE
Utsendinger - velge dato for utsending

### ISSUE THREAD

**Issue by skkrist** [Rapporteket/NORIC#118]
Slik det er per dags dato blir månedlige utsendinger sent ut for første gang samme dato, en måned frem i tid. Det vil si at dersom utsendingen er laget 1.juni, kommer første rapport 1.juli. 

Dersom man gjør endringer, f.eks endre mottakere, blir dato for utsending akkurat 1 mdn etter endringen. Så dersom det er ønskelig å få tilsendt en rapport på en spesiell dato (1. i måneden) må alle endringer gjøres samme dato - selv om det er helg, ferie..

Det hadde vært praktisk å kunne velge dato for første utsending ! 

Dette gjelder også ukentlige utsendinger.

**Comment by areedv** [comment]
Ja, jeg er klar over denne og behovet for utvidet kontroll på utsendinger. Her benyttes det funksjoner i rapbase som er felles for alle registre på Rapporteket og slike endringer må derfor foretas der. Jeg legger inn en sak i rapbase og det er mulige jeg kan begynne å gjøre noe i løpet av sommeren
