### ISSUE TITLE
Felt som mangler i AortaklaffVar

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#14]
Disse feltene finnes i datadumpene vi får lastet ned fra "gamle" Rapporteket, men er ikke i oversikten over tabeller og felt som du sendte meg per e-post tidligere i dag:

- BasisRegStatus
- ForlopsType1
- ForlopsType2
- HovedDato (viktig, kan ikke utledes)
- KobletForlopsID
- OppflgRegStatus
- PasientAlder (viktig, kan ikke utledes)
- PasientKjonn (viktig, kan ikke utledes)
- Sykehusnavn (kan utledes fra AvdRESH)
- KommuneNr (viktig, kan ikke utledes)
- Kommune (viktig, kan ikke utledes)
- Fylkenr (viktig, kan ikke utledes)
- Fylke (viktig, kan ikke utledes)

Kan du oppdatere sql-spørringen i getAKData slik at vi får med disse feltene?

**Comment by areedv** [comment]
Alle disse feltene finner du i tabellen ForlopsOversikt, se ny tab "Metadata" i oppdatert applikasjon. Tilsvarende er nå tilgjengelig under "Datadump" i oppdatert applikasjon på test-helseregister.no. Så forstår jeg det slik at du ønsker dette inn i "Utforsker", altså pivot-tablellen, (er det riktig?) og det skal jeg klare å fikse. Jeg oppfatter videre at du vil ha inn aorta-klaff i utforskeren, og det ordner jeg. Men jeg litt usikker på koblingen til feltene du angir over fordi jeg også oppfatter at disse er like relevant også for de andre datasettene...

**Comment by areedv** [comment]
Se ny utgave av 'Utforsker' og steng saken om du @ellnyg er happy...

**Comment by ellnyg** [comment]
Hei!

Supert med den Metadata-fanen med søkefunksjon! Nå ble det lettere å få oversikt over hvilke felt som finnes i de forskjellige tabellene/datadumpene.

Jeg ser at f.eks. `PasientAlder`, som er en variabel som benyttes mye, ikke finnes i andre tabeller enn *ForlopsOversikt*. Det samme gjelder `Kommune`, `ForlopsType1`, og `ForlopsType2`. Feltene `PasientID`, `PasientKjonn` og `HovedDato` kunne med fordel blitt lagt til flere tabeller enn de 1-2 tabellene som har dem per dags dato. Samtidig er det enkelte felt som er overflødige (`erMann` f.eks.) eller gjør det enklere å indirekte identifisere en pasient (`Norsktalende` f.eks.).

Kanskje det hadde vært like greit å bli enig med Siren og Svein om noen bestemte felt fra *ForlopsOversikt* som vi ønsker å ha med i *samtlige tabeller*, og så legge til disse i SQL-spørringene i getXXData-funksjonene? 

Hvis det i ettertid viser seg at enkelte felt ikke skal være i en spesifikk tabell likevel så klarer jeg å fjerne feltet fra SQL-spørringen eller ved bruk av `%>% select( -variabel_vi_vil_fjerne)`.

Jeg kan snakke med Siren neste uke (Svein er på ferie) og lage en liste over feltene vi vil ha med, hvis det høres ut som en plan, @areedv ?

**Comment by areedv** [comment]
Ja, dere i Bergen må ha et bevist forhold til hvilke variabler som skal være med i de ulike datasettene som gjøres tilgjengelige. Så kan det godt hende at vi bør flytte alle JOIN og lignende operasjoner over i R. Da flytter vi "kompleksitet" fra SQL til R noe som gjør det mer tilgjengelig for deg/NORIC å ha kontroll på hva som foregår samt at man da vil være mindre sårbar for (manglende) indeksering og spørringer som det tar lang tid å kjøre

**Comment by ellnyg** [comment]
Det høres greit ut for min del at joining foretas med R. Så lenge det ikke medfører at ting går mye saktere,

**Comment by ellnyg** [comment]
Oppretter ny issue om at Siren og Svein må enes om hvilke felt fra FO som skal finnes i alle de andre datadumpene (utenom SkjemaOversikt muligens).
