### ISSUE TITLE
Nedlasting av ForlopsOversikt via Datadumper - duplikat av HovedDato med rart navn

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#15]
Jeg har lastet ned et par forskjellige ForlopsOversikt-filer i både csv- og excel format i dag, og HovedDato har en duplikat (kolonnen helt til høyre) som heter "HovedDato..32".

Har lastet ned flere andre datadumper og kikket på dem (CT, AnP, AP) og finner ikke lignende duplikater i disse datadumpene.

**Comment by areedv** [comment]
Ja, FO gjør en join med seg sjøl (på HovedDato) og derav et ekstra og rart navn. Altså, denne følger bare den generelle malen brukt for alle tabeller (ved nedlasting) men bør altså behandles spesielt (om FO faktisk skal være nedlastbar, noe jeg er er litt usikker på)

**Comment by ellnyg** [comment]
Ang. hvorvidt FO skal være nedlastbar:
Da jeg kikket på datadumpen jeg lastet ned fra ShinyNORIC på fredag, så det ut som at KryptertFnr fungerer nå som en slags nasjonal PasientID. Slik har det ikke vært før, da har KryptertFnr tilhørende de samme individene vært forskjellig på hvert sykehus.

Hvis KryptertFnr nå har blitt unikt på nasjonal basis, så vil ForlopsOversikt være nyttig for oss å kunne fortsette å laste ned, slik vi har gjort i gamle Rapporteket. Det kan hende det bare vil være aktuelt for SC ved Haukeland, siden det stort sett er jeg som vil ha bruk for den.  Jeg må høre med Siren og Svein.

**Comment by ellnyg** [comment]
FO brukes primært av meg, så dette er ikke avgjørende å få ordnet før nyttår.

**Comment by ellnyg** [comment]
FO (fra både QA og test) er nå i orden.
