### ISSUE TITLE
Datadumper - laste ned csv-filer i Excel-vennlig format

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#16]
Har lastet ned csv-filer av Anp, AP, CT, FO og SS, og for å kunne kikke på dem i Excel  må man importere dem via "Data"/Hent data fra tekst inne i selve Excel.

Fikk du testet om det går an å bruke readr::write_excel_csv/write_excel_csv2 i stedet for rio::export?

Dette er ikke en hastesak, men å kunne klikke på en csv-fil og åpne den i Excel synes jeg gjør hverdagen litt mer lettvint.

**Comment by areedv** [comment]
Nei, jeg har ikke prioritert dette og har foreløpig bare tatt raskeste vei til målet... Denne saken kan plukkes opp senere

**Comment by ellnyg** [comment]
Filformatet xlsx-csv fungerer enn så lenge ikke slik det gjør på pc-en min når jeg bruker readr::write_excel_csv2 (da kan jeg dobbeltklikke på csv-filen og den åpnes i Excel med alle verdiene fordelt på riktig måte i separate rader og kolonner). 
Slik det er nå kommer hvert forløp på sin egen rad i Excel, men alle verdiene plasseres i samme kolonne.

Kan hende at det løser seg etter at commiten hvor write_excel_csv ble endret til write_excel_csv2 i server.R trer i kraft i TEST og i QA.

**Comment by ellnyg** [comment]
Lastet ned AortaklaffVar i nasjonal QA nå nettopp og da fungerte xlsx-csv-alternativet utmerket. 

Da jeg dobbeltklikket på datadumpen åpnet den seg i Excel, og skjønte Excel at den skulle bruke UTF-8 (æ/ø/å ble brukt istedet for Ã¸ osv).
En datadump jeg lastet ned som vanlig csv åpnet seg i Excel da jeg dobbeltklikket på den (det var ikke tilfellet før vi endret koden til at datadumpene blir lastet ned i csv2-format), men da virker ikke æ/ø/å.

Jeg tror endringen til csv2-format kan være årsaken til at det tilsynelatende fungerer slik det skal. 

Fortsetter å teste nedlastinger med xlsx-csv etter vår første release. Prioriterer ikke systematisk testing av dette nå.

**Comment by ellnyg** [comment]
Har lastet ned datadumper i både csv-format og xlsx-csv-format fra disse tabellene: 

- AndrePRosedyrerVar

- AortaklaffVar

- SegmentStent

- AngioPCIVar

Ser det samme som beskrevet tidligere (https://github.com/Rapporteket/NORIC/issues/16#issuecomment-575546137):
  
**Vanlig csv-format:*** åpnes i fint i Excel med unntak av at æ/ø/å blir til kruseduller.
 **xlsx-csv-format:** åpnes fint i Excel og har korrekt visning av æ/ø/å
