### ISSUE TITLE
Duplikate rader i nedlastet ForlopsOversikt

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#17]
Oppdaget da jeg kikket på csv-filen jeg lastet ned fra Datadumper i ShinyNORIC at ForlopsOversikt tilsynelatende har mange duplikate rader.

Csv-filen jeg lastet ned med tidsrommet f.o.m. 2013-11-22 t.o.m. 2019-11-19 med nasjonale tall har totalt 701,705 rader. 

Når jeg bruker `FO %>% distinct() %>% nrow()` så får jeg `[1] 197,156` rader.

Jeg gjorde opptelling av hvor mange rader det er i FO per unike kombinasjon av AvdRESH, PasientID, ForlopsID og ForlopsType: 
![image](https://user-images.githubusercontent.com/49942922/69429455-e1bd6380-0d33-11ea-8d2d-116ac397cee0.png)

Det ser ut som visse forløp fra AngioPCI-modulen blir firedoblet, og det forekommer for alle sykehusene;
![image](https://user-images.githubusercontent.com/49942922/69429909-e7677900-0d34-11ea-8196-e233a73c1014.png)

**Comment by areedv** [comment]
Jeg tror dette er en egenskap ved tabellen ForlopsOversikt og ikke nødvendigvis en feil...

**Comment by areedv** [comment]
Lag spesialtilfelle for FO i getDataDump()

**Comment by ellnyg** [comment]
Nå ser det ut til å være fikset!

`dump1` = datadumpen jeg lastet ned i november hvor det var duplikater,
`dump2` = en tilsvarende datadump jeg lastet ned i dag

![image](https://user-images.githubusercontent.com/49942922/70787542-2d8d8680-1d8f-11ea-9409-7c35f33f83a4.png)
