### ISSUE TITLE
Ny Prosedyrer-rapport under utvikling

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#20]
Ref. det vi snakket om nettopp på telefonen.

Kan du lage en ny fane til den nye prosedyrer-rapporten jeg holder på å lage?
Etter litt finpuss og et forsøk på å parametrisere Rmd-filen til den nye rapporten så kan jeg pushe den til rel.

**Comment by ellnyg** [comment]
Jeg må legge inn kode fra ny månedsrapport.

**Comment by ellnyg** [comment]
Ønsker å få på plass det jeg har skrevet i Rmd hittil. Hvis det blir for tidkrevende flytter vi denne til v2.1.

**Comment by skkrist** [comment]
Gå gjennom denne rapporten og sortere det som skal i månedsrapport og det som ikke lenger er aktuelt.

**Comment by skkrist** [comment]
utgått på dato
