### ISSUE TITLE
Startside

### ISSUE THREAD

**Issue by areedv** [Rapporteket/NORIC#21]
Det bør etableres en starside som inneholder kort info om hva og hvordan

**Comment by areedv** [comment]
Ser sånn ut nå:
![image](https://user-images.githubusercontent.com/1522857/70304886-37e5d880-1803-11ea-8fc6-ba2a28ee8c8a.png)

Innholdet her er definert i [inst/veiledning.Rmd](https://github.com/Rapporteket/NORIC/blob/rel/inst/veiledning.Rmd). Her kan det ved behov også legges inn grafikk og lenker

**Comment by ellnyg** [comment]
Ønsker hjelp fra Siren og Svein til å forfatte veiledningsteksten. Er kanskje mulig å bruke deler av NORIC sitt mandagsmøte for å få noe ned på papiret.

**Comment by ellnyg** [comment]
Venter på forslag til tekst fra Svein og Siren.

**Comment by ellnyg** [comment]
Fått på plass en enkel versjon. Vi kan gjenåpne saken etter produksjonsetting hvis det blir nødvendig.
