### ISSUE TITLE
Brukerrolle-avhengig tilgang til felt i tabellene

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#22]
Få klarhet i hvilke brukerroller som skal få tilgang til hvilke felt/variabler i de forskjellige datadumpene/tabellen. 
Lage et regneark med kolonnene 

- Datadump (AngioPCIVar osv)
- Variabelnavn (ForlopsID, AvdRESH, osv)
- EkstraSensitivt (Ja/Nei)
- LUtilgang (Ja/Nei)
- LCtilgang (Ja/Nei)
- SCtilgang (Ja)

og så få Siren og Svein til å fylle ut. Kan deretter leses inn i RStudio og lage kode som spesifiserer hvilke variabler som ikke skal vises for de forskjellige brukerrollene. Muligheter for å legge til mer logikk etter hvert (som f.eks. LU ved UNN får ikke tilgang til variablene x,y,z,...)

**Comment by ellnyg** [comment]
Har sendt Excel-ark til Siren og Svein for utfylling. Har bedt de tenke enkelt nå innledningsvis mtp. den forskjellige praksisen med tildeling av brukerroller ved de forskjellige sykehusene.

**Comment by ellnyg** [comment]
Opplever at det fortsatt er uenighet rundt hvordan en brukerrolle-styrt tilgang til forskjellige variabler/funksjoner bør fungere. Men vi er enig om at vi bør være restriktive innledningsvis, og heller tilpasse oss eventuelle behov som melder seg i fremtiden.
  
Jeg skal forsøkte å få klarhet i hva Siren og Svein ønsker at LC og LU skal ha tilgang til nå innledningsvis. Det har vært diskutert flere ganger uten at vi har landet på noe konkret.

**Comment by ellnyg** [comment]
Idé:
Lage en funksjon som heter noe à la `UserRoleColumnFilter()` som fungerer noenlunde slik:

`UserRoleColumnFilter <- function(tabell, userRole){`

`if( userRole == "LC"){`

`tabell %<>% `
 `  select( -contains("FodselsDato"), -contains("operator", ignore.case = T), etc... )`  
`tabell`

`}`
`}`

Bør helst være slik at funksjonen kan brukes med samtlige tabeller. Da må NORIC være konsistente med restriksjonene sine, dvs. at hvis LC ikke skal ha tilgang til kolonnen `FodselsDato` i tabellen AngioPCIVar, så må det også være slik at LC ikke skal ha tilgang til `FodselsDato` i en av de andre tabellene. Hvis det skal være forskjellig for hver tabell blir koden mer innviklet med mange `if`-setninger.

Det som er kjekt med bruk av `select( -contains("kolonne_navn")` er at koden fungerer selvom den aktuelle tabellen ikke har en kolonne som heter `kolonne_navn`.

Ved å inkludere `userRole` som et argument, legges det til rette for at man i fremtiden enklere kan inkorporere et filter for LU dersom det skulle bli besluttet at LU skal få tilgang til noen få variabler i Utforsker.

**Comment by skkrist** [comment]
etter mail fra Are i dag, disse forandringene: Flere ?

funksjonen noric::getPivotDataSet   
--> input: legge til userRole=userRole
-->Dersom variablene som skal skjules er felles for alle datasettene, legge til helt på slutten (linje 64, før "} else {") 
                 if(userRole== LU) { dat %<>% select(-var1, var2, :::, vark)}
               NB : var1, var2, ...,vark trenger ikke være tilstede i alle datasettene. select(-) tar hensyn til dette.
--> Dersom variablene er ulike per datasett, legge til den samme linjen, men med unike variabler, inni hver if-løkke

server.R
linje 26-30 : tilltate Utforsker for LU

linje 177 : legge til userRole : getPivotDataSet(..., userRole = userRole)
linje 182 : legge til userRole : getPivotDataSet(..., userRole = userRole)

**Comment by skkrist** [comment]
@maraut90 Er denne saken avlsuttet for din del ?

**Comment by maraut90** [comment]
Den er snart avsluttet. Må bare sjekke endringene i QA først.
