### ISSUE TITLE
Hva skal LU og LC ha tilgang til helt i begynnelsen?

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#23]
Få spikret helt konkret hva forskjellen mellom Rapporteket for LU og LC skal være.
  
Hittil har disse alternativene blitt nevnt:
  
1. SC har tilgang til alt, mens LU/LC kun har tilgang til rapporter
2. SC har tilgang til alt. LU har kun tilgang til rapporter. LC har tilgang til det samme som LU, samt tilgang til Utforsker (men der skal variablene FodselsDato, KommuneNr, Kommune, Fylke, OperatorNavn, o.l. ikke være tilgjengelig).

**Comment by areedv** [comment]
Foreløpig legges begrensninger på faner som kun er for SC, så får detaljene komme etter nyttår

**Comment by ellnyg** [comment]
Snakket nettopp med Svein, og han bekreftet at det var i orden at det kun er SV som får tilgang til Utforsker og nedlasting av datadumper. På sikt ønsker han at LC skal kunne bruke Utforsker, men hvor et knippe mer sensitive variabler er fjernet fra datasettene (slik som beskrevet i punkt 2 lenger oppe).

**Comment by ellnyg** [comment]
Lukker saken. Kan gjenåpnes hvis det kommer innvendinger til denne oversikten:
  
Brukerrolle: | Tilhørighet: | Får   tilgang til:
-- | -- | --
LC   eller LU | Hvilket   som helst av de 9 sykehusene | Månedsrapportene   (Prosedyrer og Stentbruk) og Abonnement.
SC | Hvilket   som helst sykehus utenom Haukeland/Helse Bergen. | Det   samme som LU og LC, i tillegg til Utforsker (med kun lokale data),   Datadump (med kun lokale data) og Metadata.
SC | Helse   Bergen | Alt.   Nasjonale data.
