### ISSUE TITLE
Duplikater i nedlastet datadump

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#27]
Ser at AngioPCIVar også har duplikate rader når man laster ned en datadump. Det kan godt hende det gjelder for de andre datadumpene også, jeg rekker ikke å sjekke,

Det kan hende det løser seg selv hvis mine endringer i getLocalXXData() implementeres, siden jeg har fjernet join med SkjemaOversikt, eller kanskje du må gjøre samme fiks som det du gjorde for å fikse ForlopsOversikt-datadumpen.

(Merry jul!)

**Comment by ellnyg** [comment]
Lastet ned nye AngioPCIVar-dumper fra test i dag, og det er fortsatt duplikate rader. 

@areedv, er det det fortsatt joinen med SO som ligger til grunn for det som lastes ned fra ShinyNoric i test?
Er det annerledes i QA?

**Comment by ellnyg** [comment]
AngioPCIVar-datadumper fra QA har også duplikate rader.

**Comment by ellnyg** [comment]
Starter med tilpasning av *getDataDump()* som avtalt på telefonen.

**Comment by ellnyg** [comment]
Har pushet ny versjon av getDataDump().
Får ikke testet den noe særlig i Helse Bergen-boblen min, men forhåpentligvis fungerer den tålelig greit.

**Comment by areedv** [comment]
Se 64249c893ac931643cf9e945f47fd25d48721c60

**Comment by ellnyg** [comment]
Tok en nøye gjennomgang av AnP, AP, CT, FO, SS og SO i dag. Ingen av disse datadumpene har duplikate rader. 
Har ennå ikke fått testet AortaklaffVar da endringen jeg gjorde i ui.R ikke har blitt videreført til test eller QA ennå.
Kan lukke saken da det trolig er i orden.
