### ISSUE TITLE
"Tenkehjul" som indikerer at skjer ting når man laster ned datadump

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#30]
Det kunne vært greit med et eller annet på Datadump-siden som indikerer at datadumpen holder på laste ned etter man har trykket på "Hent!"
Slik kan vi unngå at brukere trykker på "Hent!" flere ganger fordi det ser ut som det ikke skjer noe.

**Comment by areedv** [comment]
Ja, jeg har lagt inn et slikt "hjul" (spinner) men av en eller annen grunn som jeg og HNIKT ikke har klart å finne ut av enda så fungere ikke dette godt (nok) i QA. Så, foreløpig er det tatt vekk
