### ISSUE TITLE
Nedlasting av AngioPCIVar med data fom 2016 tom 2019 mislyktes

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#31]
Ikke nødvendigvis en bug, da dette er store mengder data. Men det bør kanskje legges til veiledende tekst på denne siden om at man for eksempel bør laste ned for et år om gangen.

Hvor mye data bør Rapporteket kunne håndtere at man laster ned om gangen?

![image](https://user-images.githubusercontent.com/49942922/71716040-bee29c80-2e13-11ea-9b78-6f48944fd0b6.png)

![image](https://user-images.githubusercontent.com/49942922/71716071-da4da780-2e13-11ea-94b0-463a23c25665.png)

**Comment by areedv** [comment]
Vi kan nok nærme oss et svar ved å teste systematisk. Inntil videre er det bare du/dere i Bergen som har tilgang til dump og da er problemet begrenset...

Og ja, gjerne mer veiledende tekst, her og ellers i applikasjonen. Det er lagt godt til rette for bruk av slik gjennom Rmd. Se eksempelvis hvordan det er gjort under "Start"-fanen

**Comment by ellnyg** [comment]
Har ikke SC-rolleinnehavere ved andre sykehus tilgang til datadump?
Og så har vi i Bergen tilgang til nasjonale datadumper?

**Comment by ellnyg** [comment]
Lukkes da den dreide seg om datadumper hvor bug'en med duplikate rader var til stede. 
Kan gjenåpnes hvis systematiske tester av nedlasting av datadumper viser lite tilfredstillende begrensninger.
