### ISSUE TITLE
Endre csv-format til datadumpene til csv2 (semikolon-separerte)

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#32]
Csv-filer som ble lastet ned fra det gamle Rapporteket var i csv2-format. Det skaper litt krøll og ekstra arbeid når jeg skal switche mellom å håndtere gamle datadumper og nye datadumper lastet ned fra ShinyNoric (som er separert med ",").

Er det i orden at jeg endrer formatet på datadumpene som lastet ned i "Datadump", @areedv ?

**Comment by areedv** [comment]
Klart. Endringen kan enklet gjøres i funksjonen contentDump() som ligger i server.R

**Comment by ellnyg** [comment]
Da har jeg endret contentDump() i server.R
Saken kan gjenåpnes hvis noe skulle skjære seg, men det er svært lite sannsynlig da det er en bitteliten endring.
