### ISSUE TITLE
CTAngioVar-datadump lastes ikke ned

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#33]
Dette skyldes trolig at jeg ved en feil har brukt PasientID som nøkkel i left_join i getDataDump, men dette feltet finnes ikke i CTAngioVar.

**Comment by ellnyg** [comment]
Har fikset getDataDump og pushet endringen til rel.
Kan du gi et vink når denne endringen er lagt over i QA, @areedv ?

**Comment by ellnyg** [comment]
Litt snodig:
Ifølge Metadata i QA så inneholder ikke CTAngioVar feltet *PasientID*.
Men ifølge Metadata i test så finnes *PasientID* i CTAngioVar.
Er nok derfor jeg får lastet ned datadumpen fra test, men ikke i QA.

**Comment by areedv** [comment]
Da er det forskjell i datagrunnlaget i TEST og QA. Så er det viktig å vite om dette skyldes en feil eller om det er resultat av ønskede endringer i NORIC. Siste versjon fra 'rel' er lagt ut i QA og hos meg fungerer nå nedlasting av CTAngioVar

**Comment by ellnyg** [comment]
Vi har måttet laste ned datadumper nesten utelukkende fra TEST så lenge jeg har jobbet her, så jeg er mer fortrolig med datagrunnlaget i TEST, enn i PROD.

Jeg vil anta at datagrunnlaget i QA/PROD blir likt datagrunnlaget i TEST når HN IKT endelig får produksjonssatt de endringene de kom med i sommer, men jeg er ikke sikker.

Jeg oppdaget nettopp at *FodselsDato* finnes i *CTAngioVar* i TEST, men ikke i QA, så dette kan gjelde flere felt og muligens i flere tabeller....

**Comment by ellnyg** [comment]
De følgende feltene finnes i CTAngioVar i TEST, men *ikke* i QA:

- Avdod
- AvdodDato
- BasisRegStatus
- FodselsDato
- FunnConcat
- Kjonn
- Lokalsykehus
- OppflgRegStatus
- PasientRegDato
- SEGMENT1
- SEGMENT10
- SEGMENT11
- SEGMENT12
- SEGMENT13
- SEGMENT14
- SEGMENT15
- SEGMENT16
- SEGMENT17
- SEGMENT18
- SEGMENT19
- SEGMENT2
- SEGMENT20
- SEGMENT3
- SEGMENT4
- SEGMENT5
- SEGMENT6
- SEGMENT7
- SEGMENT8
- SEGMENT9
- Studie


Dette skyldes trolig en feil da SEGMENT-variablene er sentrale verdier som burde vært med.

**Comment by ellnyg** [comment]
Jeg har purret på HN IKT angående prodsetting. Avventer svar fra dem før jeg gjør noe mer med koden tilhørende CTAngioVar på Datadump- og Utforsker-siden.

**Comment by ellnyg** [comment]
Lukker saken da CTAngioVar kan per dags dato lastes ned fra både test og QA. Når HN IKT omsider prodsetter slik at PROD-data ser mer fornuftig ut, kan det bli aktuelt å vurdere om *getDataDump* og *getCTData* bør tilpasses ytterligere.
Ikke helt optimalt nå, men det er ikke krise om det er slik i noen uker :)
