### ISSUE TITLE
Re-definisjon av tilganger til data og rapporter

### ISSUE THREAD

**Issue by areedv** [Rapporteket/NORIC#35]
Etter møte 14. januar gjelder følgende:

Brukerrolle: | Tilhørighet: | Får tilgang til:
-- | -- | --
LC eller LU | Hvilket som helst av de 9 sykehusene | Månedsrapportene (Prosedyrer og Stentbruk) og Abonnement.
SC | Hvilket som helst av de 9 sykehusene, men ikke det nasjonale NORIC (dvs. der hvor Svein, Siren, Kjetil og jeg er ansatt) | Det samme som LU og LC, i tillegg til Utforsker (med kun lokale data), Datadump (med kun lokale data) og Metadata.
SC | Det nasjonale NORIC (Svein, Siren, Kjetil og jeg, vi som har tilgang til «Rapporteket – Noric Nasjonal» på Helseregister.no, se skjermdumpen nedenfor) | Alt. Nasjonale data.

**Comment by ellnyg** [comment]
**Systematisk sjekk:**

Rapporteket - NORIC QA, Nasjonalt, SC: 

- [ ] Nasjonale data i Utforsker

- [ ] Nasjonale data i datadump

Rapporteket - NORIC QA, Helse Bergen, SC: 

- [ ] Kun lokale data i Utforsker

- [ ] Kun lokale data i datadump

**Comment by ellnyg** [comment]
Alt ser bra ut (se e-post). 

Denne saken kan lukkes dersom vi kommer frem til at det unødvendig å sjekke  ytterligere lokale registres QA-Rapportek 👍 Avventer avklaring.

**Comment by ellnyg** [comment]
Fikk avklart på telefon med Are at det er tilstrekkelig at jeg har sjekket Nasjonalt og Helse Bergen.
