### ISSUE TITLE
Tilpasse getDataDump() slik at flere datadumper kan lastes ned (AnD, PS, mm.)

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#36]
I forbindelse med at jeg har laget *getXXData*-funksjoner for disse tabellene:

- [x]  AnnenDiagnostikkVar

- [x]  AortaklaffOppfVar

- [x]  MitralklaffVar

- [x]  PasientStudier

hadde det vært fornuftig å legge deler av koden fra disse funksjonene over i *getDataDump()* og tilpasse den slik at vi kan laste ned disse tabellene/datadumpene i tillegg til å se på dem i Utforsker.

**Comment by ellnyg** [comment]
@areedv Er det best å vente med å endre *getDataDump()* til vi ser at de nye *getXXData*-funksjonene virker knirkefritt i QA?

**Comment by areedv** [comment]
Ny utgave er klar i QA. Det er så langt jeg kan se feil i "Utforsker" for _PasientStudier_, _Aortaklaff oppfølging_ og _Aortaklaff_ og dette er relatert til at det gjennom  ```getXXData()```-funksjonene spørres om data fra tabeller og felter som ikke finnes

**Comment by ellnyg** [comment]
Jeg har pushet en endring i *getPSData()* som muligens fikser problemet med *PasientStudier*.

Jeg tror HN-IKT har klusset litt med navnet på dette view-et. Før het den *PasientStudier*, men i gamle TEST Rapporteket og i Metadata-fanen oppgis navnet Pasient***er***Studier.

@areedv Kan du legge ut ny versjon i QA slik at jeg får sjekket om det er der skoen trykker?
Jeg har gått joinene i *getAKOppfData()* og *getAKData()* og de ser greie ut, men det kan kanskje at hende noen av feltene jeg referer til i *mutate()* ikke finnes.

**Comment by areedv** [comment]
Jeg legger ut en ny versjon etter lunsj. Du kan jo sjekke hva som faktisk ligger tilgjengelig av tabeller og felter gjennom "Metadata"...

**Comment by areedv** [comment]
Ser ut som om at _PasientStudier_ nå fungerer. De andre feiler fortsatt...

**Comment by ellnyg** [comment]
Har pushet endringer i *getAKData()*. 

Kommenterte ut mange linjer fra *mutate()* som jeg la til forrige uke. De feltene som det refereres til nå skal finnes i AortaklaffVar ifølge Metadata.
Krysser fingrene for at det virker!

**Comment by ellnyg** [comment]
@areedv Supert om du kan se litt mer på dette og legge ut ny versjon ganske kjapt. Da rekker jeg å teste dette i QA før jeg må i et møte kl 15 :)

**Comment by ellnyg** [comment]
MitralklaffOppfVar har fortsatt ingen registreringer såvidt jeg vet, så denne ble ikke tatt med i denne omgangen heller. På sikt kan vi eventuelt gjøre MitralklaffOppfVar tilgjengelig i Utforsker som et første steg.

**Comment by ellnyg** [comment]
__Testing i QA til Helse Bergen som SC:__

Nedlasting av datadump:

-  AnnenDiagnostikkVar OK

- AortaklaffOppfVar OK (fikk lastet ned csv-fil med 0 rader)

- MitralklaffVar OK

- PasientStudier OK

  
  
<br><br>  
__Testing i QA Nasjonalt HF som SC:__

Nedlasting av datadump:

-  AnnenDiagnostikkVar OK

- AortaklaffOppfVar OK

- MitralklaffVar OK

- PasientStudier OK

  
  
<br><br>  
__Testing i QA til Bodø som SC:__

Nedlasting av datadump:

-  AnnenDiagnostikkVar OK

- AortaklaffOppfVar OK (fikk lastet ned csv-fil med 0 rader)

- MitralklaffVar OK (fikk lastet ned csv-fil med 0 rader)

- PasientStudier OK (fikk lastet ned csv-fil med 0 rader)

**Comment by ellnyg** [comment]
Neste steg i testingen (om jeg får tid) er å sammenligne datadumpene lastet ned fra QA i dag med datadumper av disse tabellene som jeg lastet ned før MAR.

**Comment by ellnyg** [comment]
Tror ikke sammenligningen nevnt i https://github.com/Rapporteket/NORIC/issues/36#issuecomment-640484171 er nødvendig. Lastet ned alle de "nye" datadumpene i dag fra NORIC Nasjonal QA. Det fungerte bra og alt så greit ut da jeg kikket kjapt på csv-filene.

Vi kan heller vurdere å gjenåpne saken dersom noen oppdager feil i fremtiden.
