### ISSUE TITLE
Lage en ryddigere variant av AngioPCIVar med færre variabler til Utforsker

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#39]
Enten

1. Lage en alternativ getAPData() som dropper mindre brukte felt (alle variabler som slutter på "Ukjent", Init-medikamenter f.eks.), eller
2. tilpasse getLocalAPData() slik den returnerer et ryddigere/mindre AP hvis man spesifiserer at man ønsker dette når man kaller funksjonen (parameter reduce_rows = TRUE eller noe sånt)

Eller noe annet lurt.

Haster ikke.

**Comment by ellnyg** [comment]
Et annet forslag er å legge til nye checkboxer under "Velg alle variabler" som heter "Velg bort xxx-variabler".

Hvis man huket av for "Velg alle variabler", og deretter "Velg bort komplikasjons-variabler", så legges først alle variablene til vektoren med valgte variabler, og deretter fjernes alle komplikasjon-variablene. Dette kan gjøres ved bruk av 
`%>% select( -starts_with("AvdKomp", ignore.case = FALSE), -starts_with("LabKomp", ignore.case = FALSE) )` i getLocalAPData(). Og vips så har man 40 færre variabler enn hvis man hadde valgt alle variablene.

Hvis man ekskluderer alle variablene som begynner med SEGMENT, får man 60 færre variabler. 
(`%>% select( starts_with("SEGMENT", ignore.case = FALSE) )`)

Det er flere grupper med variabler som kan fjernes vha `select()` og `starts/ends_with`/`contains` som vi kan bruke til å fjerne flere titalls variabler fra datasettet av gangen.

En mulig ulempe er at det kan bli mange checkboxer å holde styr på.
Fordelen er at man raskt kan fjerne variabler man ikke er interessert i å se på i Utforsker som er intuitivt gruppert.

**Comment by areedv** [comment]
`getAPData()` må i så fall ta imot et nytt argument (en vektor) som spesifiserer hvilke variabler som ev skal ut av dataramma som returneres av funksjonen. Men, enda mer elegant (og tidsbesparende) vil det være om sql-en i utgangspunktet bare benyttet de variablene man faktisk skal ha

**Comment by ellnyg** [comment]
Jeg tenkte i utgangspunktet å ha et TRUE/FALSE-argument brukes som condition i en if-setning som inneholder f.eks. `%>% select( starts_with("SEGMENT", ignore.case = FALSE) ) `. Men da spørres det fortsatt om hele tabellen i SQL-spørringen ja.

Det er sikkert mulig å bruke spørringer med bruk av (gjerne case-sensitiv) `not like 'SEGMENT%'`, men det får jeg kanskje ikke testet selv. Alle eksemplene jeg finner på nettet med select-spørringer som filtrerer felt utifra navn på felt bruker information_schema.columns/andre metadata-tabeller.

**Comment by skkrist** [comment]
Dette dekkes i AP light "Angio PCI med utledete variabler", her fjernes lite brukte variabler, utledete variabler legges til.
