### ISSUE TITLE
Fjerne kolonner med ".FO"-suffiks fra datasett i getXXData()-funksjonene

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#40]
Legge til linje med
`XX %>% select( -ends_with( ".FO", ignore.case = FALSE ) )`
slik at eventuelle felt fra FO som allerede finnes i XX slettes og vi slipper at det er duplikater av felt i det resulterende datasettet som sendes til `rpivotTable()`. 

Datagrunnlaget kan endre seg (slik vi har sett med feltet PasientID i CTAngioVar). Koden blir trolig mer robust dersom `left_join( XX, FO, ....)` bruker færrest mulig felt som nøkler for å gjøre entydige koblinger, og vi deretter sletter feltene som får ".FO"-suffiks som følge av at feltet finnes i både XX og FO.

**Comment by skkrist** [comment]
Dette er ikke lenger tilfelle
