### ISSUE TITLE
Legg til nye utledete variabler til datadumper i GetXXData() og GetDataDump()

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#45]
Det er behov for variabler som

- prim_fid (den primære forløps-IDen tilknyttet et forløp)

- primart_forlop (hvorvidt et forløp er registrert som et primærforløp)

- sekundart_forlop (hvorvidt er forløp er registrert som et sekundærforløp)

- tidsdiff_ankomst_prosedyre_minutter/timer/dager

- etc.

hvor variablene kan utledes utelukkende fra kolonner som allerede eksisterer i datadumpen.
(Det er også behov for utledete variabler basert på kolonner fra andre tabeller/dumper, men det er litt mer mer omfattende og kan adresseres i egne issues).

**Comment by skkrist** [comment]
#121 lager funksjoner for dette.
