### ISSUE TITLE
Stent månedsrapport i PDF-format viser ikke alle figurer og tabeller

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#46]
De to siste stentrapportene jeg har fått tilsendt via abonnement ser merkelige ut:
  
<br>  

![image](https://user-images.githubusercontent.com/49942922/81160415-51de3f80-8f8a-11ea-8095-1d2f75a77a6b.png)
  
  
Noen figurer vises bare delvis, og enkelte tabeller ser ut til å mangle fra pdf-rapporten.
<br> 
  
Må kartlegge om dette også gjelder når man laster ned rapporten selv, og om det også gjelder html. Inkludere Prosedyrer-rapporter i kartleggingen også.

**Comment by areedv** [comment]
Joda, denne har jeg sett ikke fungerer godt som pdf. html-utgave tror jeg ser bedre ut

**Comment by ellnyg** [comment]
Ah, stemmer, det hadde jeg glemt at du har nevnt.

En mulig fiks av deler av problemet kan være å legge inn `\clearpage` eller annen Latex syntax på strategiske steder. Rmarkdown skal ignorere Tex når den bruker `'html'` som output-format (https://github.com/yihui/rmarkdown-cookbook/issues/15). Dette burde ikke ta lang tid.

Det at noen tabeller ser ut til å mangle, derimot, vil trolig kreve litt mer arbeid.

**Comment by skkrist** [comment]
v2.0.22 fikset
