### ISSUE TITLE
Prosedyrer inneholder ferskere data i nedlastet versjon enn rapporten som vises på siden  

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#47]
Når man trykker på "Prosedyrer"-fanen får man opp dette:

![image](https://user-images.githubusercontent.com/49942922/75258537-e7b95980-57e6-11ea-8640-b7ce83873ab4.png)

... men når man laster ned rapporten som html vises enda mer oppdaterte tall:

![image](https://user-images.githubusercontent.com/49942922/75258647-17686180-57e7-11ea-8c68-60d5188babe0.png)

Dette skjer ikke for rapporten Stentbruk. (Jeg har kun sjekket Rapporteket til Haukeland, venter på å bli tildelt tilgang til andre sykehus)

@areedv , har du en mistanke om hva grunnen til dette kan være?

**Comment by areedv** [comment]
Hm, denne var snedig... Skal se hva jeg finner ut

**Comment by areedv** [comment]
Jeg har prøvd med Helse Bergen HF - SC fra QA og jeg får tilsvarende tall i nettleser og nedlastet html. Kan det være at din nettleser har lagret en tidligere side som den viser deg i stedet for den oppdaterte fra Rapporteket? Prøv å slett/rydd i browser-historien, ev bare last sida på nytt

**Comment by ellnyg** [comment]
Testet det nettopp i Internet Explorer etter å ha slettet alle cookies/browsing/download history.
  
**Rapporteket - Noric, Helse Bergen HF, både SC og LC**: samme problem. Ingenting endrer seg hvis man trykker på refresh. Stentbruk har oppdaterte data i nettleser.
  
**Rapporteket - Noric QA, Helse Bergen HF, både SC og LC**: Her har Prosedyrer oppdaterte data i både nettleser og nedlastet html-fil. Samme med Stentbruk.

Merkelig :/

**Comment by ellnyg** [comment]
Siren har sjekket Rapporteket (PROD) til alle de andre sykehusene, og finner den samme uoverensstemmelsen der også.

**Comment by ellnyg** [comment]
En liten oppdatering:
  
Nå har "etterslepet" på Prosedyrer-rapporten i nettleser blitt enda større.

Nettleser (viser kun t.o.m. januar 2020, ser ut til å være uendret fra forrige gang vi så på problemet):
![image](https://user-images.githubusercontent.com/49942922/77415506-e0c03f80-6dc2-11ea-8626-03cd01118889.png)

Nedlastet html (viser t.o.m. mars 2020):
![image](https://user-images.githubusercontent.com/49942922/77415576-f9c8f080-6dc2-11ea-974b-51e41d10844c.png)

@areedv: Hvis dette er noe som potensielt kan ta litt tid å nøste opp i, er det mulig å "gjemme" rapporten i nettleser slik at man må laste den ned for å se den? Jeg tror en del brukere kan anta at vi ikke har mer oppdaterte data i Rapporteket, og at det derfor er gunstig å "nudge" dem til å laste ned rapporten.

**Comment by areedv** [comment]
Min hypotese nå er at det ligger bi-produkter av tidligere kjørte rapporter og som da (ved en feil) benyttes for å vise fram resultatet i nettleseren. Når denne feilen ikke gjelder nedlasting så er sannsynlig årsak at dette skjer i en egen prosess adskilt fra den som produserer innhold til nettleseren. Jeg har lagt inn ny versjon 2.0.4 på QA som forhåpentligvis fikser feilen. Om så lager vi en ny PR til `master` fra `rel` og legger ut i PROD. Hvis ikke får vi feilsøke videre...

**Comment by ellnyg** [comment]
Supert! Jeg har nettopp sjekket Rapporteket - Noric QA for Helse Bergen, både LU og SC, og der er feilen nå borte :) 

Nå har ikke jeg tilgang til flere lokale QA-prosjekt, men regner med at det er tilstrekkelig å bare sjekke Helse Bergen sin lokale QA.

@areedv: Hadde det vært hensiktsmessig å få løst #50 og lagt dette over i QA før det legges ut en ny versjon i PROD? Slå gjerne på tråden hvis du har tanker om dette.

**Comment by areedv** [comment]
Fint. Jeg lukker saken nå men tror det er viktig at dere følger litt ekstra med på at verdiene faktisk oppdaterer seg med tiden (og at det vi ser nå kun er resultat av at ny versjon av R-pakken er lagt ut)

**Comment by ellnyg** [comment]
Oppdaget nå at jeg hadde helt glemt at feilen ikke var tilstede i QA i i utgangspunktet, kun i PROD. Det er iallefall det jeg skrev i kommentaren ovenfor: 
https://github.com/Rapporteket/NORIC/issues/47#issuecomment-591304525
:) 

Så det at feilen ikke er tilstede i QA er intet nytt.

**Comment by ellnyg** [comment]
Fungerer bra ut i PROD enn så lenge👍 Må sjekke neste uke om det holder seg.
Testet i Rapporteket - Noric Helse Bergen HF (LU og SC) og Nasjonalt (SC)

**Comment by ellnyg** [comment]
Diskrepansen gjør et comeback, og nå finner jeg den også i QA.

## Sjekk av **Rapporteket - Noric, Helse Bergen SC**

### **I nettleser (Chrome):**

![image](https://user-images.githubusercontent.com/49942922/78539770-62689200-77f3-11ea-8272-60bde7a34ba0.png)


### **I nedlastet html (Chrome):**

![image](https://user-images.githubusercontent.com/49942922/78539679-3e0cb580-77f3-11ea-9477-30ba55d1ab39.png)

Det samme forekommer for LU, og når jeg bruker Edge som nettleser (jeg har ikke brukt Edge til å logge meg inn i Rapporteket i løpet av de siste 2 ukene). Jeg slettet all nettleser-data i Chrome fra de siste 7 dagene og logget inn på nytt, men feilen er der fortsatt.
  
<br>  

  
## Tilsvarende sjekk i **Rapporteket - Noric QA**, Helse Bergen SC. 

*Her er diskrepansen større enn i Rapporteket - Noric.*

### **I nettleser (Chrome):**

![image](https://user-images.githubusercontent.com/49942922/78540968-32ba8980-77f5-11ea-9333-2902e4d37199.png)

### **I nedlastet html (Chrome):**

![image](https://user-images.githubusercontent.com/49942922/78541070-5bdb1a00-77f5-11ea-8c5e-a7cc03ffcc9d.png)

**Comment by ellnyg** [comment]
@areedv Vet du om andre registre har støtt på samme bug i sine Rapportek?

**Comment by ellnyg** [comment]
Are og jeg pratet om denne bug-en på telefonen i dag. 
  
Diskrepansen mellom Prosedyrer i nettleser og Prosedyrer i nedlastet html-format er fortsatt tilstede i både QA og PROD (SC-rolle, Helse Bergen). Stentbruk fungerer fortsatt bra (ingen diskrepans). Om nødvendig, kan det være aktuelt å undersøke hva som skiller nedlasting av Stentbruk og Prosedyrer kodemessig for å nøste opp i hvor feilen ligger.
  
Oppdaget at nedlasting av PDF ikke fungerer som det skal. @areedv kan vurdere om det bør opprettes en egen issue i forbindelse med dette.

**Comment by areedv** [comment]
Feilen KAN ligge i måten ```knit::knitr()``` fungerer; fra dokumentasjonen om argumentet _output_:
> Path to the output file for knit(). If NULL, this function will try to guess a default, which will be under the current working directory.

Det betyr at produktet (html-filen som vises i nettleseren) etableres der prosessen kjører (og ikke i en temporær filkatalog) men fremdeles med et temporært (og unikt) navn. Selv om det første ikke er ønsket så skal temporært navn sørge for at oppdatert html-fil vises frem og ikke en som ligger igjen fra en tidligere kjøring (som mest sannsynlig er årsaken til feilen). Uansett, det blir gjort et nytt forsøk der hele prosessen kjøres i en temporær filkatalog (tilsvarende nedlasting) for å se om det hjelper

**Comment by ellnyg** [comment]
Lite utdrag fra rapporten Prosedyrer i Rapporteket - Noric QA, Helse Bergen (SC) for fremtidig referanse.

__I nettleser:__
![image](https://user-images.githubusercontent.com/49942922/81275665-43f3f180-9052-11ea-8ac8-f3da6c75f049.png)
  
<br>

__I nedlastet html-rapport:__
![image](https://user-images.githubusercontent.com/49942922/81275854-8ae1e700-9052-11ea-80e7-1a9f6290bd4c.png)
  
<br>

Bør sjekkes på nytt neste uke.

**Comment by ellnyg** [comment]
Ny sjekk av Prosedyrer-rapporten i Rapporteket - Noric QA, Helse Bergen (SC).

I nettleser:
![image](https://user-images.githubusercontent.com/49942922/81813813-3a71fa00-9528-11ea-8236-2e1e17bd18de.png)


I nedlastet html:
![image](https://user-images.githubusercontent.com/49942922/81815083-dcdead00-9529-11ea-888d-f67a5ba8276a.png)

**Comment by ellnyg** [comment]
Begge sjekkene ovenfor ble utført i Chrome på samme PC. 
Jeg tar en ny sjekk om noen dager, og lukker saken dersom det fortsatt er samsvar mellom rapport i nettleser vs. nedlastet rapport på det tidspunktet.

**Comment by ellnyg** [comment]
__Fra nettleser i HB sin QA med SC-rolle:__
  
  
![image](https://user-images.githubusercontent.com/49942922/82420191-afd94f80-9a7f-11ea-9eab-d8cdea635c3d.png)

 <br> 
  
__Nedlastet html fra HB sin QA med SC-rolle:__
  
![image](https://user-images.githubusercontent.com/49942922/82421490-5f62f180-9a81-11ea-8ad6-830f1ac456dc.png)

  
<br>
Opplever at lasting av rapporten i nettleser tar lengre tid enn det som var tilfellet i den tiden det ikke var samsvar mellom rapporten i nettleser og i nedlastet versjon. Dette kan tyde på at nå lastes rapporten inn på nytt hver gang; som er det vi ønsker.
<br><br>     
Lukker saken da den tilsynelatende er løst.
