### ISSUE TITLE
Legge til variabelen "ferdigstilt" fra SO til aktuelle tabeller 

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#48]
Det hender ofte at brukerne ønsker å ekskludere ikke-ferdigstilte forløp fra diverse opptellinger i Utforsker da disse forløpene ofte er mindre komplette og tidvis ikke kvalitetssikret.

Legge til en join til SO i `getXXData()` slik at variabelen "ferdigstilt" kan utledes fra "SkjemaStatus".
Tilsvarende kan med fordel også gjøres i `getDataDump()`.

**Comment by ellnyg** [comment]
Første steg i denne prosessen kan være å kun legge til "ferdigstilt"-variabelen til et mindre hyppig brukt datasett i Utforsker som f. eks. AndreProsedyrerVar.

Jeg kan forsøke å gjøre alt i SQL hvis dette er å foretrekke. Det er en såpass enkel operasjon at det ikke er noe problem å skrive en spørring.

**Comment by areedv** [comment]
Veldig bra

**Comment by ellnyg** [comment]
Tabeller/datadumper hvor det er ønskelig å legge til kolonner om status (hvorvidt de er ferdigstilt eller ikke) for aktuelle skjema (skjemastatus ligger lagret i SkjemaOversikt):
  

- [ ] AndreProsedyrerVar

- [ ] MitralklaffVar

- [ ] AortaklaffOppf

- [ ] AnnenDiagnostikk, tilhører AngioPCI-modulen (Start-, AngioPCI-, Kompl- og Utskrivelse-skjema)

- [ ] CTAngioVar

- [ ] SegmentStent, tilhører AngioPCI-modulen (Start-, AngioPCI-, Kompl- og Utskrivelse-skjema)

- [ ] AortaklaffVar (denne innregistreringsmodulen ble nylig delt opp i 2 skjema, må undersøke hvordan dette utspiller seg i SkjemaOversikt)

- [ ] AngioPCIVar, tilhører AngioPCI-modulen (Start-, AngioPCI-, Kompl- og Utskrivelse-skjema)


Tabellene øverst i listen er naturlige å starte med da de brukes sjeldnere enn tabellene nederst på listen. Dersom en join mellom f.eks. AndreProsedyrerVar og SkjemaOversikt forårsaker at `getLocalAnPData()` krasjer og at AndreProsedyrerVar ikke er tilgjengelig i Utforsker, så er dette mye mindre kritisk enn om tilsvarende skulle skje med AngioPCIVar.

__Nye SQL-spørringer som viser seg å fungere bra i `getXXData()`-funksjoner etter omfattende testing i QA (eller TEST) kan deretter inkorporeres i `getDataDump()`.__
