### ISSUE TITLE
Enklere men ryddig bruk av funksjoner i dplyr mm

### ISSUE THREAD

**Issue by areedv** [Rapporteket/NORIC#5]
Har laget et forslag til bruk av slike funksjoner ref vår diskusjon på fredag (da jeg muligens har kommet i skade for å gi dårlige råd...). Målet er å unngå overflødig kode og bevare god oversikt. Alle endringer er vist i https://github.com/Rapporteket/NORIC/commit/1a92ead44c3e59f55238dcf58d8b07b56f183932 men de endringer som er relevant å vurdere ligger (enn så lenge) i funksjonen ```getLocalCTData()```. Oppsummert er det da snakk om å bruke ```importFrom``` for de funksjoner som er i bruk fremfor ```require()``` eller eksplisitte referanser (```::```)

**Comment by ellnyg** [comment]
Da skal dette forhåpentligvis være fikset i alle getLocalXXData-funksjonene i shinify

**Comment by areedv** [comment]
Nais
