### ISSUE TITLE
Legge til utledete variabler som uke, maaned, etc. i getAKData()

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#50]
Da jeg forsøkte å legge til variabler som `aar`, `maaned`, `uke`, og `kvartal` i `getAKData()` før jul, så skapte det feilmeldinger for en eller annen merkelig grunn. Det ble derfor lagt på is frem til vi fikk første versjon av nye Rapporteket opp å gå.
  
Nu er det dags for å forsøke igjen. Det er mange nyttige opptellinger som er umulig for brukerne å utføre i Utforsker uten disse variablene (og da kontakter de meg, og så må jeg gjøre det for dem).

**Comment by areedv** [comment]
Legg inn dine endringer av `getAKData()` i en PR så kan vi se på det sammen deretter

**Comment by ellnyg** [comment]
Både jeg og Svein mener at det ser greit ut.

**Comment by ellnyg** [comment]
Ser bra ut i PROD 👍 
Testet i Rapporteket - Noric Helse Bergen HF (LU og SC) og Nasjonalt (SC)
