### ISSUE TITLE
Mer utfyllende beskrivelse på Start-siden

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#52]
Kan med fordel legges til veiledning.Rmd: 
    
Beskrivelse av forskjellen mellom nedlastningsalternativene "csv" og "xlsx-csv" i Datadumper.
  
Muligens mer også. Må høre med Siren og Svein om de har fått tilbakemeldinger fra andre brukere,

**Comment by ellnyg** [comment]
Kan også være lurt å legge til på Start-siden at månedsrapportene fungerer ofte bedre dersom man laster dem ned i html-format fremfor PDF (frem til vi får fikset #46 ).

**Comment by ellnyg** [comment]
Forslag som må luftes med ledelsen i NORIC:
Skrive på Start-siden at tips/ønsker om forbedringer av Rapporteket kan sendes per e-post til fellespostkassen til NORIC (ev. merket med et konkret ord i emnefeltet slik at de lettere kan søke frem disse e-postene og gå gjennom dem med jevne mellomrom).

**Comment by ellnyg** [comment]
I tillegg til navnet på organisasjonen (som per dags dato står øverst på siden) kunne vi også inkludert tekst hvilken brukerrolle (LU/LC/SC) brukeren er innlogget med.
Dette hadde vært spesielt nyttig i forbindelse med testing i Rapporteket. Man kan fort glemme om man er logget inn som LU eller LC f.eks., og dette er ofte relevant informasjon når man skal beskrive en bug.

**Comment by ellnyg** [comment]
__Idé:__

Inkludere tekst øverst som viser noen få nøkkeltall for sykehuset (eller andre interessante tall) til brukeren. 
F.eks. "I NORIC er det per 19.05.2020 registrert xx,xxx angiografier og PCI ved SUS."

Rent teknisk:
Kjøre en spørring mot AngioPCIVar (slik som i `getLocalAPData()`) inne i chunk i i Rmd-filen veiledning.Rmd. SQL-spørringen inneholder kun relevante felt/kolonner.

Deretter bruke \` `r AP %>% pull(ProsedyreDato) %>% max( na.rm = T ) `  \` i teksten for å vise den seneste datoen som finnes i tabellen (gir bruker en indikasjon på hvor oppdaterte dataene er), og \` `r AP %>% nrow()`  \` for å oppgi antall prosedyrer som er registrert i datagrunnlaget til sykehuset hittil.

**Comment by skkrist** [comment]
Må oppdateres om LC-rolle og ny tilgang
