### ISSUE TITLE
Utforsker - raskere henting av kolonnenavn og SQL-spørring med kun nødvendige kolonner

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#61]
(Denne saken opprettes ikke med en forventning om å få implementert en løsning eller utbedring i nærmeste fremtid, men mer som et forslag/notat for fremtidig referanse 😃 )

Etter man har valgt et datasett fra nedtrekkslisten i Utforsker tar det ofte litt tid før `getXXData()` har hentet dataene og det er mulig å velge variabler og deretter laste valgte data.

Det kan hende dette forslaget koster mer enn det smaker, men en mulig måte å utbedre dette på kunne vært at:
  
1. En innledende SQL-spørring i `getXXData()` spør kun om den første raden i de aktuelle tabellene ( "SELECT TOP 1 * FROM tabell")  
  
2. Det resulterende datasettet (med kun 1 rad) brukes i shiny-appen slik at bruker kan velge ut variablene hen ønsker.
  
3. Når bruker trykker på "Last valgte data!" kjøres det en ny SQL-spørring hvor det kun spørres om de kolonnene som brukeren ønsker. 

Noe som gjør dette litt utfordrende er bruken av avledete variabler som utarbeides i R, og det faktum at sentrale variabler som `Sykehusnavn` og `Pasientkjonn` hentes fra ForlopsOversikt (og det er også planlagt i implementere joins med SkjemOversikt). 

En avledet variabel som skal utarbeides med R-kode kan f.eks. være avhengig av kolonnene "ProsedyreDato" og "ProsedyreTid", og disse kolonnene er det ikke gitt at brukeren velger. Å få 
  

- A) oversikt over kolonnene hver enkelt avledet variabel er avhengig av, og 

- B) implementert dette på en fornuftig og relativt vedlikeholdsfri måte, 

virker utfordrende fra mitt ståsted.

Det er selvsagt mulig å lage avledete variabler med SQL, men per dags dato ville dette trolig vært ganske tungvint å få implementert og testet da registeret ikke har tilgang til et fornuftig utviklingsmiljø (enn så lenge).

**Comment by skkrist** [comment]
Bruk av single-row hjelper. Dette er gjort her for alle tabeller: https://github.com/Rapporteket/NORIC/releases/tag/v2.4.1

Dersom begrenset tidsvindu vil innlasting gå raskere! #125
