### ISSUE TITLE
Stentbruk viser ikke alle stentmerker

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#63]
Linje 379 i `NORIC_local_monthly_stent.Rmd` gjør slik at stentmerker som utgjør en veldig liten andel av registrerte merker i løpet av de siste 12 månedene ekskluderes fra tabellene "Antall stenter etter merke og måned" og "Prosent andel stenter etter merke og måned".

https://github.com/Rapporteket/NORIC/blob/98ea9e350156f659dba0962cd5124b7d294affc7/inst/NORIC_local_monthly_stent.Rmd#L378
https://github.com/Rapporteket/NORIC/blob/98ea9e350156f659dba0962cd5124b7d294affc7/inst/NORIC_local_monthly_stent.Rmd#L379

Det som kan være litt uheldig med dette er at et stentmerke som utgjorde en betydelig andel i f.eks. januar ikke tas med i tabellene fordi merket ble brukt i mindre enn 1% av alle stent-innsettelsene i løpet av de siste 12 månedene. Siden radene i "Prosent andel stenter etter merke og måned" summerer til 100% kan det tolkes slik at tabellen gir et uttømmende bilde selv om dette ikke alltid er tilfellet.
  
Jeg tror at enten bør ordlyden i rapporten endres slik at det kommer tydelig frem at det kun er de mest brukte stentmerkene som vises, eller så må det (i dialog med ledelsen i NORIC) gjøres justeringer i koden slik at alle merkene vises eller det lages en "Annet merke" kategori. 
Hvis sistnevnte blir omfattende å få implementert, kan det ev. vurderes å lage en ny versjon av rapporten slik den opprinnelige forfatteren selv foreslo i 2018.

**Comment by areedv** [comment]
Dette er ikke en "bug" men heller en (uønsket) "egenskap". Kanskje vi heller skulle lage en egen label for denne type uønskede egenskaper

**Comment by ellnyg** [comment]
Enig!
