### ISSUE TITLE
Prosedyrer-rapporten; nedlasting virker ikke og rester fra tidligere kompilerte rapporter vises

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#64]
__Beskrivelse og skjermdumper fra i går da feilen først ble oppdaget:__

Jeg får lastet ned Stentbruk, men ikke Prosedyrer. Det eneste formatet som virker (av og til) når jeg skal laste ned Prosedyrer er "BEAMER" og det formater fungerer ikke optimalt da 

Når jeg velger html som format og trykker på "Hent!" vises dette når jeg skal velge filplasseringer til rapporten:
![image](https://user-images.githubusercontent.com/49942922/82889051-76ef1e00-9f4a-11ea-8857-0f2fa1a2d2a2.png)
![image](https://user-images.githubusercontent.com/49942922/82890307-401a0780-9f4c-11ea-83b4-ee7a3ba73f6c.png)

(Merk at filnavnet ikke er slik det pleier.)

Etter jeg har valgt filplassering og trykket på "Lagre" vises dette i nettleser (Chrome):
![image](https://user-images.githubusercontent.com/49942922/82889208-b158bb00-9f4a-11ea-94b8-d7a56851a41a.png)

Ikke samme utfordring med Stentbruk:
![image](https://user-images.githubusercontent.com/49942922/82890526-a0a94480-9f4c-11ea-988b-af323d2a0a82.png)

<br><br>
I tillegg migrerer datagrunnlaget fra Prosedyre-rapporter jeg har sett på i nettleser på andre sykehus sine Shiny-apper over til Prosedyrer-rapporten i nettleser til helt andre sykehus. 
  
I dette eksempelet vises Bodø sine data inne på Haukeland sin Shiny-app:

![image](https://user-images.githubusercontent.com/49942922/82896185-cdae2500-9f55-11ea-8f6e-898d4c431ad0.png)

Stentbruk fungerer forbilledlig (slik var det også i forbindelse med #47).

**Comment by ellnyg** [comment]
__Fra testing i QA i morges:__

Jeg gikk inn på Bodø først.
  
Fortsatt problemer med nedlasting av Prosedyrer-rapporten (gjelder alle format og både SC/LC/LU):
![image](https://user-images.githubusercontent.com/49942922/82994945-37d0d380-a003-11ea-9236-5dc7eac3e597.png)
   
<br> 
  
Deretter gikk jeg inn på Helse Bergen.  
  

Prosedyrer-rapporten i nettleser viser tall fra korrekt datagrunnlag:
![image](https://user-images.githubusercontent.com/49942922/82995821-6602e300-a004-11ea-8463-bdf316aca946.png)      
   
<br><br>   
  
Rapporten ser ut til å bruker litt tid på å når jeg bytter "profil" (dvs. logger ut fra Helse Bergen som SC, og deretter inn som LC). 
Dette er lovende og kan tyde på at 24a5fd54077fed25c8796599b9c1d8d673b9c0dc kanskje var løsningen på problemet med migrerende datagrunnlag.
<br><br>

Nedlasting-funksjonaliteten er ustabil i QA. 

Da jeg logget inn på Helse Bergen, SC, for første gang i dag, gikk det ikke an å laste ned noen av formatene. Fem minutter senere, da jeg logget inn i HElse Bergen som LC, fikk jeg lastet ned alle formatene. 
  
HTML lastet ned fra Helse Bergen, LC, ser slik ut:
![image](https://user-images.githubusercontent.com/49942922/82997290-79af4900-a006-11ea-804b-ed66fc867d9a.png)  

  

<br><br>   
      
Jeg logget inn som SC igjen ved Helse Bergen rett etterpå, og virket plutselig nedlastingen der inne også. Det samme gjaldt dessverre ikke for Bodø - jeg fikk ikke lastet noen av formatene som verken LU, LC eller SC.
  
Stentbruk fungerer tilsynelatenende bra hos alle sykehusene og med alle brukerrollene i QA.

**Comment by ellnyg** [comment]
Nå har jeg hoppet mye frem og tilbake mellom Bodø og Helse Bergen i QA, og Prosedyrer viser fortsatt tall fra riktig datagrunnlag i nettleser. Finner fremdeles feilen i PROD når jeg bytter mellom sykehus.
  
Kan se ut som problemet med migrerende datagrunnlag er fikset, men for å være mer sikkert bør utfordringen med nedlasting av Prosedyrer-rapporten løses slik at jeg kan sjekke nedlastede versjoner av Prosedyrer.

**Comment by areedv** [comment]
Prosedyre-rapporten i kombinasjon med data fra Bodø bør kjøres isolert. Min hypotese er manglende/utilstrekkelige data fra Bodø pt og at dette bryter med forutsetninger (eks mellomregninger) i rapport-templatet(Rmd-filen). Klarer du @ellnyg å teste dette hos deg? Jeg har ikke tilgang til data fra Bodø...

**Comment by ellnyg** [comment]
@areedv Jeg kan prøve å gjenskape det lokalt på min PC med datadumper fra Bodø 👍 
Men burde det ikke være mulig å laste ned rapporten når den vises i html i nettleresen uten problemer?

**Comment by ellnyg** [comment]
Se etter ledetråder her i morgen: https://github.com/rstudio/shiny/issues/2152

**Comment by ellnyg** [comment]
De eneste mellomregningene jeg kan si med sikkerhet skaper warnings under kompilering av `NORIC_local_monthly.Rmd` med Bodø-data er chunks som omhandler AnP (Andre Prosedyrer) da Bodø ikke har registrert noen forløp i denne modulen ennå. 
  
I nettleser ser AnP-delene av Prosedyrer slik ut:
![image](https://user-images.githubusercontent.com/49942922/83129440-1e9c5580-a0dd-11ea-9950-272556459635.png)
  
Rapporten kompileres og vises i nettleser til tross for ingen data i AnP. Det kan derfor virke som det skjer noe i `downloadHandler()`-delen av `server.R` som forårsaker problemet siden det som skjer inne i `renderUI()` ser ut til å fungere fint.

**Comment by areedv** [comment]
Ser at (bruken av) funksjonen ```contentFile()``` i server.R burde forbedres. Nå benyttes alltid samme filnavn til mellomlagring av rapportene (_tmpNoricStent.Rmd_ og _tmpNoric.Rmd_). Å gi disse et unikt navn, ```tempfile(fileext = ".Rmd")```, hver gang vil være en ekstra forsikring mot at innhold kan "gjenbrukes" fra gang til gang. Hvilken grein vil da ha denne endringen i @ellnyg ? Forøvrig så tror jeg ikke lenken over er relevant for vårt tilfelle. Utelukker det ikke, men vi får heller komme tilbake til denne

**Comment by ellnyg** [comment]
Har laget en grein di kan bruke som heter `dev` @areedv .
Ble litt krøll med gamle lokale greiner hos meg så kunne ikke kalle den rel som avtalt :)

**Comment by ellnyg** [comment]
Å legge `dev` over i QA ser ut til å fikset buggen 👍 
Jeg endrer tilbake til `include=FALSE` i `dev` og pusher på nytt slik at vi slipper de unødvendige R-utskriftene i rapporten.

**Comment by ellnyg** [comment]
Nedlasting av både Stentbruk og Prosedyrer virker i PROD (testet som SC ved både Nordlandssykehuset og Helse Bergen). Sjekket både html og pdf. Nettleser viste like oppdaterte tall som i nedlastede versjoner.

**Comment by ellnyg** [comment]
Har hoppet frem og tilbake mellom Nordlandssykehuset og Helse Bergen innenfor et kort tidsrom (under 5 minutter) og opplever ikke at "rester" fra tidligere kompilerte rapporter ved ett lokalt register dukker opp i nettleseren eller de nedlastede rapportene til et annet lokalt register.

Har også hoppet frem og tilbake mellom andre sykehus innenfor et kort tidsrom, og alt er tilsynelatende i orden med datagrunnlaget som brukes til månedsrapportene Stentbruk og Prosedyrer.

Lukker saken da alt bugen tilsynelatende er fikset.
