### ISSUE TITLE
Mer effektiv spørring mot ForlopsOversikt i getDataDump()

### ISSUE THREAD

**Issue by ellnyg** [Rapporteket/NORIC#68]
Koden per dags dato:

https://github.com/Rapporteket/NORIC/blob/24a5fd54077fed25c8796599b9c1d8d673b9c0dc/R/getDataDump.R#L88

ForlopsOversikt har svært mange linjer (spesielt i den nasjonale databasen) og det kan med fordel spørres etter en delmenge av tabellen i forbindelse med nedlasting av datadumper.

Et alternativ er å lage en R-funksjon som kalles fra inne i `getDataDump()` som tar `tableName`  som en parameter og lager en mer effektiv SQL-spørring.   
Dette kan oppnås ved å legge til linjen 
`WHERE ForlopsType1 IN ('Angio', 'Angio+PCI', 'PCI')` i tilfeller hvor `tableName = 'AngioPCIVar'` for eksempel, slik at det ikke brukes unødvendig tid og krefter på å hente radene tilhørende forløp i AortaklaffVar, CTAngioVar, etc.
Når `tableName = 'SegmentStent'`, holder det å returnere rader hvor `ForlopsType1 = Angio+PCI` eller `PCI` siden det ikke utføres perkutane intervensjoner under rene Angio-forløp.
  
Å filtrere ForlopsOversikt basert på dato er neppe den beste løsningen da den ikke inneholder ProsedyreDato, men HovedDato, og feilregistreringer kan medføre at disse datoene er langt unna hverandre i tid.
  
  
Dette behøver ikke prioriteres med én gang da nåværende løsning har fungert tilfredsstillende bra hittil, men tabellene blir bare større og større...

**Comment by skkrist** [comment]
Stor ryddejobb utført. Dette er da mindre aktuelt. 
https://github.com/Rapporteket/NORIC/releases/tag/v2.4.1
