### ISSUE TITLE
Ny måndelig rapport - Kvalitetsindikatorer

### ISSUE THREAD

**Issue by skkrist** [Rapporteket/NORIC#80]
Lage en ny månedlig rapport. 
Innhold : Kvalitets-indikatorene fra årsrapporten.
I første omgang uten indikatorene som omhandler variabelen "avdød".

Det ønskes at indikatorene for hvert sykehus kan sammenliknes med nasjonale tall.

Skal kobling mellom to tabeller f.eks. AngioPCI og SS gjøres med SQL-spørring eller med r-kode?

**Comment by areedv** [comment]
Teknisk sett er det mulig å koble lokale og nasjonale tall. Valgt av metode bør presenteres for- og godkjennes av registeret slik at sammenstillingen av tall fra ulike registre er akseptabelt, formelt sett.

SQL er bestandig utgangspunktet for uthenting av tall, men kan også benyttes som verktøy for tilrettelegging og bearbeiding av datasett. Hvor mye av det siste som legges til SQL og R, hhv, må vurderes ut fra hvert enkelt tilfelle/behov. I de fleste tilfeller vil det være lurt å bruke SQL til å hente ut og avgrense datasettet for deretter å benytte R til nødvendig "massasje" før presentasjon

**Comment by maraut90** [comment]
Etter møtet 15. januar 2021 var det ønsket at det sendes ut pdf-månedsrapport fra det nasjonale rapporteket til de lokale rapportekene.  
Om det er mulig er det ønsket at forsiden også inneholde hvem som mottar pdf-filen som vi vet ut i fra e-postlisten. 
Månedsrapporten skal kun inneholde hele måneder og i noen tilfeller skal kvalitetsindikatorene kun vise kvartalsvise tall.

**Comment by skkrist** [comment]
gjort ! v2.1.0
