### ISSUE TITLE
Månedsrapport -  Melding: "Rapport genereres - vennligst vent"

### ISSUE THREAD

**Issue by skkrist** [Rapporteket/NORIC#81]
Ha et symbol, eller en tekst, som sier "Rapport genereres - vennligst vent", eller noe lignende, mens rapporten lages. 
Er dette en mulighet?

**Comment by areedv** [comment]
Ja, det har allerede vært laget, men fungerte ikke på Rapporteket av årsaker vi tidlig i 2020 ikke klarte å finne ut av... Vi kan eventuelt gjøre et nytt forsøk nå. Vi kan også endre rapporten(e) for å redusere tidsbruken når de produseres

**Comment by areedv** [comment]
Dette er varianten som tidligere ikke ville virke på Rapporteket men som vi kan prøve på nytt ("snurrehjul):
![image](https://user-images.githubusercontent.com/1522857/100065564-378b8680-2e34-11eb-93d7-600948b5cbba.png)

**Comment by skkrist** [comment]
Løsning med "Loading..." fungerer fint
