### ISSUE TITLE
Nye datasett i Utforsker

### ISSUE THREAD

**Issue by areedv** [Rapporteket/NORIC#9]
Legg til "spesialiserte" datasett for bruk i pivot-tabeller. Gjøres ved å lage nye getLocalDataXXData-funksjoner

**Comment by ellnyg** [comment]
Siren og Svein mente dette ikke behøver å prioriteres før nyttår.

**Comment by ellnyg** [comment]
Dette kan vi vente med til etter første release.

**Comment by ellnyg** [comment]
På det forrige fagrådsmøtet til NORIC ble det ytret ønsker om et datasett skreddersydd for å se på utført **FFR/iFR/IVUS/OCT**. 

Her må NORIC i tenkeboksen om strukturen av et slikt datasett da en del registrert informasjon om disse metodene er i long-format i AnnenDiagnostikk (flere rader per unike forløp), mens annen informasjon er i wide-format i AngioPCIVar.

**Comment by ellnyg** [comment]
Det er ytret ønsker om et datasett skreddersydd for å se på __komplikasjonsrelaterte__ tall og problemstillinger. 

Tabellene som inneholder informasjon om __komplikasjoner på lab og avdeling__ er strukturert slik at hver type komplikasjon har sin egen kolonne med Ja/Nei/Ukjent/null som mulige verdier, og det kan være registrert flere typer komplikasjoner tilknyttet ett forløp/en rad i tabellen.

Jeg har bedt om eksempler på hva ledelsen i NORIC ser for seg i form av skjemdump eller skisse.
Denne type spesialisert datasett er også aktuell ifbm. opptellinger av __medikamenter__, hvor det benyttes samme type wide-format som for komplikasjoner.

**Comment by skkrist** [comment]
#121 Lager et nytt datasett med utledete variabler, f.eks IFR/FFR som nevnt over. 
#109 tar for seg bare behandling av komplikasjoner
Lukker derfor denne issuen
