### ISSUE TITLE
Missing var in Mitralklaff

### ISSUE THREAD

**Issue by areedv** [Rapporteket/NORIC#94]
```r
Warning: Error in : Problem with `mutate()` input `ForlopsType2`.
x argument 4 is empty
ℹ Input `ForlopsType2` is `factor(...)`.
  135: <Anonymous>
```

![image](https://user-images.githubusercontent.com/1522857/100622084-ba26b100-3320-11eb-90ad-655d8d3da586.png)

**Comment by areedv** [comment]
@maraut90 Kan du forklare hvorfor du gjør om til factor fom l 107 i ```getMKData()```? Er hensikten å rekode verdier som finnes i disse variablene (ForlopsType2, Frailty, Hastegrad, osv.)?

**Comment by maraut90** [comment]
Det var en kommafeil i koden.
Ja, jeg mener hensikten her er å rekode verdier.
